fix: remove response body from 204 response in DELETE /id
h11 throwed a
h11._util.LocalProtocolError: Too much data for declared Content-Length

because 204 response should not contain a message body, check this link
for more information (first paragraph):

https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.3