Return str version of BSON on deserializer
Returning an ObjectId causes 500 error
> ValueError: [TypeError("'ObjectId' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]